/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author Danis
 */
public class Menu extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Menu
     */
    public Menu() {
    this.setContentPane(fondo);
        initComponents();
        this.setTitle("MENU");
        
                Thread hilo = new Thread(){
            public void run(){
                while(true){
                    DateFormat hora = new SimpleDateFormat( "dd/MM/yyyy hh:mm:ss aa");
                    String h2 = hora.format(new Date()).toString();
                    reloj.setText(h2);
                }
            }
        };
        hilo.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        seccionpos = new javax.swing.JButton();
        seccionclien = new javax.swing.JButton();
        seccionmateri = new javax.swing.JButton();
        prove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel5.setText("Menú de administrador");

        seccionpos.setBackground(new java.awt.Color(204, 255, 204));
        seccionpos.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        seccionpos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logomaterial1.jpg"))); // NOI18N
        seccionpos.setText("Sección de postres");
        seccionpos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionposMouseClicked(evt);
            }
        });
        seccionpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccionposActionPerformed(evt);
            }
        });

        seccionclien.setBackground(new java.awt.Color(255, 255, 153));
        seccionclien.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        seccionclien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clienteslogo1.jpg"))); // NOI18N
        seccionclien.setText("Sección de clientes");
        seccionclien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionclienMouseClicked(evt);
            }
        });
        seccionclien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccionclienActionPerformed(evt);
            }
        });

        seccionmateri.setBackground(new java.awt.Color(204, 255, 255));
        seccionmateri.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        seccionmateri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/materialeslogo1.jpg"))); // NOI18N
        seccionmateri.setText("Sección de materiales");
        seccionmateri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seccionmateriMouseClicked(evt);
            }
        });
        seccionmateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccionmateriActionPerformed(evt);
            }
        });

        prove.setBackground(new java.awt.Color(204, 204, 255));
        prove.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedoresoficial1.jpg"))); // NOI18N
        prove.setText("Sección de proveedores");
        prove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logousuario1.jpg"))); // NOI18N
        jButton1.setText("Sección de usuarios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seccionmateri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seccionclien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seccionpos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(prove)
                .addGap(45, 45, 45)
                .addComponent(seccionmateri)
                .addGap(49, 49, 49)
                .addComponent(seccionclien)
                .addGap(42, 42, 42)
                .addComponent(seccionpos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        reloj.setBackground(new java.awt.Color(204, 204, 255));
        reloj.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        reloj.setText("jLabel1");
        reloj.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seccionposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionposMouseClicked
        Postres ps = new Postres();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seccionposMouseClicked

    private void seccionclienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionclienMouseClicked
        Clientes cl = new Clientes();
        cl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seccionclienMouseClicked

    private void seccionclienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccionclienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccionclienActionPerformed

    private void seccionmateriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seccionmateriMouseClicked
        Materiales mat = new Materiales();
        mat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seccionmateriMouseClicked

    private void seccionmateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccionmateriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccionmateriActionPerformed

    private void proveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveMouseClicked
        Proveedores prove = new Proveedores();
        prove.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_proveMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Usuarios usu = new Usuarios();
        usu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this, "¿Deseas salir?","Salir", a);
       if(resultado==0){
        System.exit(0);
       }else{}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seccionposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccionposActionPerformed

    }//GEN-LAST:event_seccionposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton prove;
    private javax.swing.JLabel reloj;
    private javax.swing.JButton seccionclien;
    private javax.swing.JButton seccionmateri;
    private javax.swing.JButton seccionpos;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel
{
    private Image imagen;
            
    @Override        
    public void paint(Graphics g)
    {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/fondomenu2.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }      
}
}

